# Generated by Django 3.2.6 on 2023-06-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=3)),
                ('node_loc', models.CharField(max_length=10)),
                ('temp', models.CharField(max_length=5)),
                ('hum', models.CharField(max_length=5)),
                ('light', models.CharField(max_length=5)),
                ('snd', models.CharField(max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
